@csJwtError_HostAddress = https://localhost:7059
@jwtToken = eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJVc2VyIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZWlkZW50aWZpZXIiOiJWdWxjYW5MZWUiLCJleHAiOjE3Mzc5ODgwMDgsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6NTAyOSIsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6NTAyOSJ9.tdXJakAEC8EKB3k7-pv4rrl67gxXJfnd4BRXrwFZqV2Hz9xZybg4LUgV_RiqzkIkSWSbDH_Y7YD4jvmFDflVug

GET {{csJwtError_HostAddress}}/weatherforecast/

###

GET {{csJwtError_HostAddress}}/login

###

GET {{csJwtError_HostAddress}}/test
Authorization: Bearer {{jwtToken}}

###
